name: flutter_phasmohelper
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  acme_theme: ^0.8.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  go_router: ^10.1.2
  # google_mobile_ads: ^5.1.0
  intl: any

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "icons/ghost_by_freepick.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/evidence/dots.png
    - assets/evidence/mrozne.png
    - assets/evidence/orb.png
    - assets/evidence/pismo.png
    - assets/evidence/spiritbox.png
    - assets/evidence/ultrafiolet.png
    - assets/evidence/emf.png
    - assets/background/background.jpg
    - assets/background/background.png
    - assets/background/background_start.jpg
