name: flutter_phasmohelper
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  go_router: ^10.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  acme_theme: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:
 generate: true
 uses-material-design: true
 assets:
   - assets/dots.png
   - assets/mrozne.png 
   - assets/orb.png 
   - assets/pismo.png 
   - assets/spiritbox.png
   - assets/ultrafiolet.png  
   - assets/emf.png  
